version: '3'
services:
  app:
    image: node:14
    container_name: app_main
    restart: always
    command: sh -c "npm install && node server.js"
    ports:
      - 4000:4000
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB: test
  mongo:
    image: mongo
    container_name: app_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongo:/data/db
volumes:
  mongodb:
