apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: nodejs-sample
  namespace: developer
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: nodejs-sample
spec:
  build:
    env:
      - name: BP_NODE_VERSION
        value: "18.17.1"
      - name: BP_NODE_RUN_SCRIPTS
        value: "server"

